src/Entity/Jury.php
<?php

namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints\EqualTo;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\JuryRepository")
 * @UniqueEntity(
 *  fields= {"mail"},
 *  message= "L'email que vous avez indiqué est déjà utilisé!"
 * )
 */
class Jury implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $fName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mail;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Note", mappedBy="jury", cascade={"remove"})
     */
    private $note;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Type", inversedBy="juries")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type;

    /**
     * @Assert\EqualTo(propertyPath="password", message="Vos mot de passe sont différent ")
     */
    public $confirmPassword;

    /**
     * @ORM\Column(type="integer")
     */
    private $firstlogin;

    public function __construct()
    {
        $this->note = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFName(): ?string
    {
        return $this->fName;
    }

    public function setFName(string $fName): self
    {
        $this->fName = $fName;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }


    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection|Note[]
     */
    public function getNote(): Collection
    {
        return $this->note;
    }

    public function addNote(Note $note): self
    {
        if (!$this->note->contains($note)) {
            $this->note[] = $note;
            $note->setJury($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        if ($this->note->contains($note)) {
            $this->note->removeElement($note);
            // set the owning side to null (unless already changed)
            if ($note->getJury() === $this) {
                $note->setJury(null);
            }
        }

        return $this;
    }

    public function getFirstlogin(): ?int
    {
        return $this->firstlogin;
    }

    public function setFirstlogin(int $firstlogin): self
    {
        $this->firstlogin = $firstlogin;

        return $this;
    }

    public function getType(): ?Type
    {
        return $this->type;
    }

    public function setType(?Type $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->mail;
    }

    public function eraseCredentials()
    {}

    public function getSalt(){}

    public function getRoles(){
        return ['ROLE_JURY'];
    }

}

templates/elements/footer.html.twig
<footer>
        <div class="footbody">
            <p>Simplon 2018</p>
            <p class="sepa">|</p>
            <p>All Right Reservered </p>
            <p class="sepa">|</p>
            <a href="#">
                <p>Mentions Légales</p>
            </a>
            <p class="sepa">|</p>
            <a href="#">
                <p>BackDoor</p>
            </a>
        </div>
      
      
</footer>

templates/elements/form.html.twig
{% block form_row %}
{% spaceless %}
    <div class="form_row">
        <div class='error_msg'>
        {% if not form.vars.valid %}
        <i class="fas fa-exclamation-circle"></i>
        {% endif %}
        {{ form_errors(form)}}
        </div>
        {{ form_widget(form) }}
    </div>
{% endspaceless %}
{% endblock form_row %}

templates/elements/nav.html.twig
<nav id="nav">
    <div class="logo">
      {% if app.user is null %}
      <a href="{{path('homepage')}}">y
      {% elseif app.user.roles[0] == "ROLE_ADMIN" %}
      
      <a href="{{path('accueilAdmin')}}">
      {% endif %}
      
      <img src="{{asset('/img/logosimplon.png')}}" alt="" >
      </a>
    </div>
    <div class="logores">
      <img src="{{asset('/img/logo-couleur.png')}}" alt="">
    </div>
    <div class="navbar">
      <div class="">
        <a href="#">A propos</a>
      </div>
      <div class="">
        <a href="#">Les Projets</a>
      </div>
      <div class="">
        <a href="#">Les Stages</a>
      </div>
      <div class="">
        <a href="#">Nous Aider</a>
      </div>
      {% if app.user is not null %}
      <a href="{{path('logout')}}" class="button">
          deconnexion
      </a>
      {% else %}
      <a href="{{path('login')}}" class="button">
          BackDoor
        </a>
      {% endif %}
      
    </div>
    <div class="burger-menu">
          <div class="bar">
            <span class="bar-1"> </span>
            <span class="bar-2"> </span>
            <span class="bar-3"> </span>
          </div>
    </div>
  
    </nav>
    <div class="menu">
      <li>
          <a href="#">A propos</a>
      </li>
      <li>
          <a href="#">Les Projets</a>
      </li>
      <li>
          <a href="#">Les Stages</a>
      </li>
      <li>
          <a href="#">Nous Aider</a>
      </li>
      <li>
          <a href="{{path('login')}}">Backdoor</a>
      </li>
    </div>
  

templates/elements/pagination.html.twig
<div class="paginationbar">
    <ul class="pagination">
        <li class="page-item {% if page == 1 %}disable{% endif %}">
            <a class="page-link" href="{{path(route, {'page': page - 1 })}}">&laquo;</a>
        </li>
        {% for i in 1..pages %}
        <li class="page-item {% if page == i %}active{% endif %}">
            <a class="page-link" href="{{path(route, {'page': i })}}">{{i}}</a>
        </li> 
        {% endfor %}
        <li class="page-item {% if page == pages %}disable{% endif %}">
            <a class="page-link" href="{{path(route, {'page': page + 1 })}}">&raquo;</a>
        </li>
    </ul>
</div>

templates/elements/sousnav.html.twig
    {% if app.user is null %}
        
    {% elseif app.user.roles[0] == "ROLE_SECRETARY" and app.user.firstlogin == 0 %}
    <div id="sousMenu">
        <div class="sousTitle"><a href="{{path('addUser')}}">Ajout de dossier</a></div>
        <div class="sousTitle"><a href="{{path('listeUser')}}">Liste des dossiers</a></div>
    </div> 

    {% elseif app.user.roles[0] == "ROLE_ADMIN" and app.user.firstlogin == 0 %}
    <div id="sousMenu">
        <div class="sousTitle"><a href="{{path('session')}}">Voir la session</a></div>
        <div class="sousTitle"><a href="{{path('gestionSecretary')}}">Gestion Secretaire</a></div>
        <div class="sousTitle"><a href="{{path('gestionUser')}}">Gestion Utilisateur</a></div>
        <div class="sousTitle"><a href="{{path('gestionJury')}}">Gestion Jury</a></div>
    </div> 
    {% endif %}
    